# -*- coding: utf-8 -*-
"""computer_play.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6Q_1yp5Ng9pRpq3_ykinLo_oszC5Ohg
"""

def computer_play(self, current_state):
    player = self.current_player(current_state)
    print(f"Computer turn, he is playing with {player}")

    actions = self.available_actions(current_state)
    next_expected_states = [
        self.take_action(current_state, action)
        for action in actions ]

    utility_values = [
        self.MinMax(state)
        for state in next_expected_states ]

    best_value = min(utility_values)
    index = utility_values.index(best_value)
    player, col = actions[index]
    print(f"Computer decided to play in column {col}")

    new_state = self.take_action(current_state, actions[index])

    self.display_grid(new_state)

    return new_state