# -*- coding: utf-8 -*-
"""human_vs_human

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9YyItIHmYYxQVyG5UA0eKHFDBVrvvoa
"""

def human_vs_human(self, current_state):
    new_state = current_state

    while self.check_terminal(new_state) == "Not terminal":
        print("_")


        player = self.current_player(new_state)
        print(f"It is {player}'s turn")


        while True:
            try:
                col = int(input("Enter column (0 to 6): "))

                if col < 0 or col > 6:
                    print("Invalid column. Choose between 0 and 6.")
                    continue

                if not self.is_valid_move(new_state, col):
                    print("This column is full. Choose another one.")
                    continue

                break

            except ValueError:
                print("Invalid input. Please enter a number.")


        action = (player, col)


        new_state = self.take_action(new_state, action)


        self.display_grid(new_state)


        result = self.check_terminal(new_state)
        if result != "Not terminal":
            if result == 1:
                print("Player X won!")
            elif result == -1:
                print("Player O won!")
            else:
                print("Draw!")
            break

    return new_state